---
title: "RStudio Connect Audit Update"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
```

```{r include = FALSE}
library(httr)
library(tidyr)
library(xml2)
library(pins)


board_register("rsconnect", server = "https://colorado.rstudio.com/rsc")

# Retrieve Pin
df_full <- pin_get("katie/rsc_content_list", board = "rsconnect")
        
# # Use the /v1/content endpoint to retrieve the full list of content items
# result <- GET(
#   paste0(Sys.getenv("CONNECT_SERVER"),"__api__/v1/content"),
#     add_headers(Authorization = paste("Key", Sys.getenv("CONNECT_API_KEY"))))
# 
# # Create a tibble for the content list result response
# df_full <- unnest_wider(tibble::tibble(dat = content(result)), dat) 

df_full
```


```{r include=FALSE}

# Write the full content list reponse out to a CSV file for download
write.csv(select(df_full, -git), "rsc-basic-audit.csv", row.names=FALSE)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

- **There are `r nrow(df_full)` content items on the server**

### Chart C

```{r}

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
library(dplyr)
library(reactable)
library(xml2)
library(pins)

# Filter the full response to select specific fields for viewing
df_view <- df_full %>%
  select(name, title, owner_guid, app_mode, access_type, r_version, py_version, created_time, last_deployed_time)

# cross with the user pin to map owner_guid to username
df_users <- pin_get("katie/user-info", board = "rsconnect")
user_lookup <- df_users %>% select(username, guid)

df_view <- df_view %>% left_join(user_lookup, by = c("owner_guid" = "guid")) %>%
  relocate(username, .after = title) %>% relocate(owner_guid, .after = last_deployed_time)

# Use reactable to create a nicely formatted table
reactable(df_view, searchable = TRUE, highlight = TRUE, resizable = TRUE,
  filterable = TRUE, columns = list(
  name = colDef(name = "Name"),
  title = colDef(name = "Title"),
  username = colDef(name = "Username"),
  # dashboard_url = colDef(name = "Content URL", cell = function(value) {
  #   htmltools::tags$a(href = value, target = "_blank", "Link")
  #   }),
  app_mode = colDef(name = "Type"),
  access_type = colDef(name = "Access Level"),
  r_version = colDef(name = "R Version"),
  py_version = colDef(name = "Python Version"),
  created_time = colDef(name = "Created", format = colFormat(datetime = TRUE)),
  last_deployed_time = colDef(name = "Last Deployed", format = colFormat(datetime = TRUE))
))
```


